In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats

tips = sns.load_dataset("tips")
titanic = sns.load_dataset('titanic')
titanic.dropna(inplace=True)
penguins = sns.load_dataset("penguins")
iris = sns.load_dataset('iris')
dia = sns.load_dataset("diamonds")


In [2]:
from sklearn import preprocessing

In [3]:
iris.iloc[:,:-1]

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [4]:
from sklearn import preprocessing
standard_scaler = preprocessing.StandardScaler()
robust_scaler = preprocessing.RobustScaler()
minmax_scaler = preprocessing.MinMaxScaler()
normalize_scaler = preprocessing.Normalizer()

In [5]:
standard_iris = standard_scaler.fit_transform(iris.iloc[:,:-1])
robust_iris = robust_scaler.fit_transform(iris.iloc[:,:-1])
minmax_iris = minmax_scaler.fit_transform(iris.iloc[:,:-1])
normalize_iris = normalize_scaler.fit_transform(iris.iloc[:,:-1])

In [6]:
pd.DataFrame(normalize_iris)

0         1         2         3
0    0.803773  0.551609  0.220644  0.031521
1    0.828133  0.507020  0.236609  0.033801
2    0.805333  0.548312  0.222752  0.034269
3    0.800030  0.539151  0.260879  0.034784
4    0.790965  0.569495  0.221470  0.031639
..        ...       ...       ...       ...
145  0.721557  0.323085  0.560015  0.247699
146  0.729654  0.289545  0.579090  0.220054
147  0.716539  0.330710  0.573231  0.220474
148  0.674671  0.369981  0.587616  0.250281
149  0.690259  0.350979  0.596665  0.210588

[150 rows x 4 columns]

In [14]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_valid,y_train,y_valid = train_test_split(iris.iloc[:,0:3], iris.iloc[:,-2])

In [8]:
from sklearn.pipeline import make_pipeline

In [10]:
from sklearn import preprocessing

In [9]:
from sklearn.linear_model import ElasticNet

In [13]:
model = make_pipeline(preprocessing.StandardScaler(),
                      ElasticNet(alpha=0.1, l1_ratio=0.2))

In [26]:
model.fit(x_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('elasticnet', ElasticNet(alpha=0.1, l1_ratio=0.2))])

In [29]:
model.predict(x_valid)

array([1.45430022, 1.66979838, 0.16405906, 1.95866125, 1.36260042,
       2.10813848, 1.42954541, 0.36396997, 0.25575885, 0.34196299,
       1.5496719 , 1.43504107, 1.86328957, 0.25943074, 1.26722874,
       1.84495448, 0.32270384, 1.70189696, 0.37038968, 2.25761572,
       1.47355936, 0.29060526, 1.23880205, 0.49051617, 1.90180786,
       1.51482549, 1.77800949, 0.98478559, 1.54692407, 1.6762181 ,
       0.35755025, 1.49923823, 1.4863988 , 0.8930858 , 0.38597694,
       0.35755025, 1.4579721 , 0.32637573])

In [31]:
poly = preprocessing.PolynomialFeatures(degree=2, include_bias=True)

In [34]:
poly.fit_transform(x_train)

array([[ 1.  ,  4.8 ,  3.  , ...,  9.  ,  4.2 ,  1.96],
       [ 1.  ,  6.  ,  2.7 , ...,  7.29, 13.77, 26.01],
       [ 1.  ,  5.  ,  3.5 , ..., 12.25,  4.55,  1.69],
       ...,
       [ 1.  ,  5.8 ,  4.  , ..., 16.  ,  4.8 ,  1.44],
       [ 1.  ,  7.7 ,  2.6 , ...,  6.76, 17.94, 47.61],
       [ 1.  ,  5.9 ,  3.2 , ..., 10.24, 15.36, 23.04]])

In [54]:
model = make_pipeline(preprocessing.StandardScaler(),
                      preprocessing.PolynomialFeatures(degree=2,include_bias=False),
                      ElasticNet(alpha=0.1, l1_ratio=0.2, random_state=42)
                     )

In [55]:
model.fit(x_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('polynomialfeatures', PolynomialFeatures(include_bias=False)),
                ('elasticnet',
                 ElasticNet(alpha=0.1, l1_ratio=0.2, random_state=42))])

In [56]:
model.predict(x_valid)

array([1.49569286, 1.67900429, 0.03163775, 1.96735222, 1.43434971,
       2.11958189, 1.50192446, 0.36074305, 0.1724688 , 0.37418866,
       1.60174843, 1.46666872, 1.83362045, 0.29572063, 1.29490974,
       1.86777864, 0.36733708, 1.72516463, 0.29175668, 2.20583813,
       1.53927601, 0.25447991, 1.27642103, 0.44826256, 1.92381781,
       1.57765134, 1.82667991, 0.98713057, 1.60155968, 1.71487026,
       0.38719799, 1.57823212, 1.44573742, 0.93465154, 0.3964926 ,
       0.38719799, 1.44263934, 0.3874592 ])

In [57]:
model = make_pipeline(preprocessing.PolynomialFeatures(degree=2,include_bias=False),
                      preprocessing.StandardScaler(),
                      ElasticNet(alpha=0.1, l1_ratio=0.2, random_state=42)
                     )

In [58]:
model.fit(x_train,y_train)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures(include_bias=False)),
                ('standardscaler', StandardScaler()),
                ('elasticnet',
                 ElasticNet(alpha=0.1, l1_ratio=0.2, random_state=42))])

In [59]:
model.predict(x_valid)

array([1.44889999, 1.67391794, 0.15916312, 2.02954309, 1.35736237,
       2.2914309 , 1.39239808, 0.34720316, 0.2801191 , 0.31240804,
       1.54773096, 1.47003751, 1.86362777, 0.24830459, 1.21997781,
       1.88240057, 0.32163823, 1.69807643, 0.33591998, 2.48792516,
       1.52746047, 0.32153809, 1.18458904, 0.49081334, 1.96503246,
       1.52068272, 1.8471004 , 0.95341214, 1.51498874, 1.72271869,
       0.35351523, 1.50932445, 1.37502739, 0.858756  , 0.38743561,
       0.35351523, 1.35352017, 0.2744993 ])